name: react-spa-devcontainer-template

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../../:/workspace:cached
      - node_modules:/workspace/node_modules
    tty: true

volumes:
  node_modules:
